### PR TITLE
Godot 4 update

### PR DESCRIPTION
**Pull request by jomiq**
Minimal work done to run the demo project on latest development build of godot.

### CODE REVIEW

**Comment by Dimev** [comment]
Nice!
I'll merge it to a seperate branch until godot 4 is fully released

**Comment by Dimev** [comment]
done, on the godot4 branch

**Comment by Dimev** [comment]
Looks like 4.0 just released, I'll test this and make a few changes if needed, then merge.

**Comment by jomiq** [comment]
I adjusted to make it run on Godot 4.0 official build. I haven't done testing apart from running the project and observing that it seems to work. 

I made this PR on a 64 bit build of Godot, but the official build has 32 bit floats (apparently?), so loading the project updated the project file. As is now (aligned with official build) is probably how you should merge it, but it's in a separate commit if you want to do it some other way.

**Comment by Dimev** [comment]
Ah thanks, I'll run it myself before merging

**Comment by Dimev** [comment]
I'm currently kinda waiting for the arch repo to update their godot to 4.0, but if that doesn't happen by the end of the week I'll probably just grab the official one.

**Comment by Dimev** [comment]
Rip, looks like the way the depth texture changed, so now it doesn't seem to be correct anymore

**Comment by Dimev** [comment]
Nvm, they also updated the docs

**Comment by Dimev** [comment]
Merged!

**Comment by Dimev** [comment]
along with some other improvements

**Comment by jomiq** [comment]
> Nvm, they also updated the docs

Yes, there was even a hint in the shader editor telling me how to update to use explicit depth texture. 👍

**Comment by Dimev** [comment]
Yep, although they also seemed to have changed the way the projection worked, as the atmosphere dissapeared behind the planet if I went far away.

That's luckily fixed now, as the docs also got changed to do it correctly again.

**Pull request merged**
